# Generated by Django 4.1.4 on 2023-05-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_staffprofile'),
        ('administration', '0002_alter_department_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='members',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='authentication.staffprofile'),
        ),
    ]
