# Generated by Django 4.1.4 on 2023-05-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_staffprofile_department_of'),
        ('administration', '0003_department_members_alter_department_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.staffprofile'),
        ),
    ]
