# Generated by Django 4.1.4 on 2023-06-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_department_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='created_by',
        ),
    ]
