# Generated by Django 4.1.4 on 2023-06-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_profile_alter_user_role_delete_staffprofile_and_more'),
        ('administration', '0005_remove_department_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
