# Generated by Django 4.1.4 on 2023-04-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_fa',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
