# Generated by Django 4.1.4 on 2023-04-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_two_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_two_fa',
            field=models.BooleanField(default=True),
        ),
    ]
