# Generated by Django 4.1.4 on 2023-05-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_department_members_alter_department_created_by'),
        ('authentication', '0004_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='department_of',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.department'),
        ),
    ]
