# Generated by Django 4.1.4 on 2023-06-14 08:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_department_created_by'),
        ('authentication', '0006_alter_staffprofile_department_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('cell', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'profiles',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('System Admin', 'System Admin'), ('Clerk', 'Clerk'), ('Dispatch', 'Dispatch'), ('Stakeholder', 'Stakeholder')], max_length=50),
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.profile'),
        ),
    ]
