# Generated by Django 4.1.4 on 2023-06-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_profile_alter_user_role_delete_staffprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_two_fa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_fa',
        ),
    ]
